// <auto-generated />
using EntityFrameworkStartingPoint.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFrameworkStartingPoint.Migrations
{
    [DbContext(typeof(SuperheroesContext))]
    [Migration("20190516205917_ChangeUsersToManyToManyRound2")]
    partial class ChangeUsersToManyToManyRound2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityFrameworkStartingPoint.Data.ToDo", b =>
                {
                    b.Property<int>("ToDoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ToDoId");

                    b.ToTable("ToDos");
                });

            modelBuilder.Entity("EntityFrameworkStartingPoint.Data.ToDoAssignedUsers", b =>
                {
                    b.Property<int>("ToDoAssignedUsersId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ToDoId");

                    b.Property<int>("UserId");

                    b.HasKey("ToDoAssignedUsersId");

                    b.HasIndex("ToDoId");

                    b.HasIndex("UserId");

                    b.ToTable("ToDoAssignedUsers");
                });

            modelBuilder.Entity("EntityFrameworkStartingPoint.Data.Universe", b =>
                {
                    b.Property<int>("UniverseId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("ParentCompany");

                    b.HasKey("UniverseId");

                    b.ToTable("Unvierses");
                });

            modelBuilder.Entity("EntityFrameworkStartingPoint.Data.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EntityFrameworkStartingPoint.Data.ToDoAssignedUsers", b =>
                {
                    b.HasOne("EntityFrameworkStartingPoint.Data.ToDo", "ToDo")
                        .WithMany("AssignedUsers")
                        .HasForeignKey("ToDoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EntityFrameworkStartingPoint.Data.User", "User")
                        .WithMany("ToDoAssigneds")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
